### ISSUE TITLE
The issuer connector does not correspond to the signed consumer

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#527]
After restarting the consumer connector, I'm getting the following error when trying to consume a resource that previously could be consumed:
```
021-08-20 10:16:23,050 https-jsse-nio-8080-exec-5 ERROR org.apache.camel.processor.errorhandler.DefaultErrorHandler - Failed delivery for (MessageId: C3D10433117AB1F-0000000000000018 on ExchangeId: C3D10433117AB1F-0000000000000018). Exhausted after delivery attempt: 1 caught: io.dataspaceconnector.exception.ContractException: The issuer connector does not correspond to the signed consumer.. Processed by failure processor: FatalFallbackErrorHandler[Channel[direct://handleInvalidTransferContract]]
Message History (complete message history is disabled)
--------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[artifactRequestHan] [artifactRequestHan] [                                                                              ] [        42]
Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
io.dataspaceconnector.exception.ContractException: The issuer connector does not correspond to the signed consumer.
	at io.dataspaceconnector.service.usagecontrol.ContractManager.validateTransferContract(ContractManager.java:114) ~[classes!/:6.0.0]
	at io.dataspaceconnector.camel.processor.handler.PolicyValidator.processInternal(IdsValidator.java:180) ~[classes!/:6.0.0]
	at io.dataspaceconnector.camel.processor.handler.PolicyValidator.processInternal(IdsValidator.java:147) ~[classes!/:6.0.0]
	at io.dataspaceconnector.camel.processor.handler.IdsValidator.process(IdsValidator.java:80) ~[classes!/:6.0.0]
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:66) ~[camel-support-3.11.0.jar!/:3.11.0]
```

**Comment by juliapampus** [comment]
Which version are you using?

**Comment by sebplorenz** [comment]
6.0.0

**Comment by juliapampus** [comment]
Should be fixed with v6.1.0. The configuration in v6.0.0 had an issue while storing the configuration. The connector id was not persisted and the connector generated a new one on every restart.

**Comment by juliapampus** [comment]
linked to issue #539

**Comment by sebplorenz** [comment]
I'm still getting this error with DSC 6.1.1 when logging to the Clearing House.
What does it mean: "issuer connector does not correspond to the signed consumer"? What is the issuer connector and what is the signed consumer? Should they be equal? Maybe it would help if the actual and expected values would be in the logs.
This is my current log:
```
2021-09-08 09:23:00,191 https-jsse-nio-8080-exec-5 INFO  de.fraunhofer.ids.messaging.core.daps.DapsVerifier - Claims verified successfully
2021-09-08 09:23:00,227 https-jsse-nio-8080-exec-5 INFO  de.fraunhofer.ids.messaging.protocol.http.IdsHttpService - URL is valid: https://logging.test.mobilitydataspace.io/messages/log/40cd6f78-248b-49a3-a1cd-fd7f2a440a55
2021-09-08 09:23:00,227 https-jsse-nio-8080-exec-5 INFO  de.fraunhofer.ids.messaging.core.config.ClientProvider - Ok Http Client Protocols[h2, http/1.1]
2021-09-08 09:23:00,227 https-jsse-nio-8080-exec-5 INFO  de.fraunhofer.ids.messaging.core.config.ClientProvider - Ok Http Client Protocols[h2, http/1.1]
2021-09-08 09:23:00,227 https-jsse-nio-8080-exec-5 INFO  de.fraunhofer.ids.messaging.protocol.http.IdsHttpService - Request is HTTPS: true
2021-09-08 09:23:01,164 https-jsse-nio-8080-exec-5 INFO  de.fraunhofer.ids.messaging.protocol.http.IdsHttpService - {
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
  "@type" : "ids:MessageProcessedNotificationMessage",
  "@id" : "https://w3id.org/idsa/autogen/MessageProcessedNotificationMessage/65f55943-8774-4320-88d8-57fd49a528ed",
  "ids:issued" : {
    "@value" : "2021-09-08T09:23:00.599Z",
    "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
  },
  "ids:issuerConnector" : {
    "@id" : "https://clearinghouse.aisec.fraunhofer.de/"
  },
  "ids:recipientConnector" : [ {
    "@id" : "https://ids.db-connector.test.mobilitydataspace.io"
  } ],
  "ids:securityToken" : {
    "@type" : "ids:DynamicAttributeToken",
    "@id" : "https://w3id.org/idsa/autogen/dynamicAttributeToken/f80f533d-ce2e-4cdd-8f7b-b7806ef4ed58",
    "ids:tokenValue" : "eyJ0eXAiOiJKV1QiLCJraWQiOiJkZWZhdWx0IiwiYWxnIjoiUlMyNTYifQ.eyJzY29wZXMiOlsiaWRzYzpJRFNfQ09OTkVDVE9SX0FUVFJJQlVURVNfQUxMIl0sImF1ZCI6Imlkc2M6SURTX0NPTk5FQ1RPUlNfQUxMIiwiaXNzIjoiaHR0cHM6Ly9kYXBzLmFpc2VjLmZyYXVuaG9mZXIuZGUiLCJuYmYiOjE2MzEwOTI5ODAsImlhdCI6MTYzMTA5Mjk4MCwianRpIjoiTVRjeE1EVTJNRFk0TWprM05UQXdNemd6TWpNPSIsImV4cCI6MTYzMTA5NjU4MCwic2VjdXJpdHlQcm9maWxlIjoiaWRzYzpCQVNFX1NFQ1VSSVRZX1BST0ZJTEUiLCJyZWZlcnJpbmdDb25uZWN0b3IiOiJodHRwOi8vaWRzLmR3ZC1jb25uZWN0b3IudGVzdC5tb2JpbGl0eWRhdGFzcGFjZS5pby5kZW1vIiwiQHR5cGUiOiJpZHM6RGF0UGF5bG9hZCIsIkBjb250ZXh0IjoiaHR0cHM6Ly93M2lkLm9yZy9pZHNhL2NvbnRleHRzL2NvbnRleHQuanNvbmxkIiwidHJhbnNwb3J0Q2VydHNTaGEyNTYiOiJhYWQzMzVlNzk4YTc0ODQwOTI5NzEwZjU3ZWI2MjQ3ZDBjM2VmZjUzZWM3MTllMTBkMGQwMWVlNzM5NGJhMDFlIiwic3ViIjoiN0M6NDM6MDU6RUE6MkU6OTg6OUU6N0Q6NjM6MUU6OTA6NTQ6N0I6OEU6MTE6MTM6RjM6MTQ6Q0U6QTA6a2V5aWQ6Q0I6OEM6Qzc6QjY6ODU6Nzk6QTg6MjM6QTY6Q0I6MTU6QUI6MTc6NTA6MkY6RTY6NjU6NDM6NUQ6RTgifQ.oSGqT1f3MVHxo-Q4DfN4suDM7MuFoyZyGRA56I7RFEw-i06oMmj_8Nkld3RGWtJZJfgBD6Iqz7CmoGrGSUuriPFUmteWaVHc1Wuc0sCL4b9t2k1Lmm27PFZLhjl48MjhVzeLZsSxSMb-Y_dMwQD4JOjB82p2WrObny3oRwdn91krX-HfGHBIOlpce20FQZfxu93wYuF3t1UiamMFhC7CwafOkLSlc3gxhUZQQQeRUSwXO1NS_1aoN3WMz6VL3e7rcQLP8PB2a_igsaXgdsIJOPNfv1Sw9m6ytR1qod_rM0KC69cmoAn0gmokkSJaLnZ6iCzw6Ameb7-Coll2PcArBg",
    "ids:tokenFormat" : {
      "@id" : "idsc:JWT"
    }
  },
  "ids:senderAgent" : {
    "@id" : "https://clearinghouse.aisec.fraunhofer.de"
  },
  "ids:recipientAgent" : [ {
    "@id" : "https://ids.db-connector.test.mobilitydataspace.io"
  } ],
  "ids:correlationMessage" : {
    "@id" : "https://w3id.org/idsa/autogen/logMessage/3189c530-5f2d-441c-bbb9-06462bd6f512"
  },
  "ids:modelVersion" : "4.0.0"
}
2021-09-08 09:23:01,167 https-jsse-nio-8080-exec-5 INFO  de.fraunhofer.ids.messaging.protocol.http.IdsHttpService - Received response passed SHACL Validation.
2021-09-08 09:23:01,176 https-jsse-nio-8080-exec-5 WARN  de.fraunhofer.ids.messaging.protocol.http.IdsHttpService - Could not deserialize Playload Could not extract class from input message
2021-09-08 09:23:01,176 https-jsse-nio-8080-exec-5 WARN  de.fraunhofer.ids.messaging.protocol.http.IdsHttpService - Skipping Connector-SecurityProfile Attribute!
2021-09-08 09:23:01,178 https-jsse-nio-8080-exec-5 INFO  de.fraunhofer.ids.messaging.core.daps.DapsVerifier - Claims verified successfully
2021-09-08 09:23:01,213 https-jsse-nio-8080-exec-5 ERROR org.apache.camel.processor.errorhandler.DefaultErrorHandler - Failed delivery for (MessageId: 7E6860D94210750-0000000000000F99 on ExchangeId: 7E6860D94210750-0000000000000F99). Exhausted after delivery attempt: 1 caught: io.dataspaceconnector.common.exception.ContractException: The issuer connector does not correspond to the signed consumer.. Processed by failure processor: FatalFallbackErrorHandler[Channel[direct://handleInvalidTransferContract]]

Message History (complete message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[artifactRequestHan] [artifactRequestHan] [                                                                              ] [      1018]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------

io.dataspaceconnector.common.exception.ContractException: The issuer connector does not correspond to the signed consumer.
	at io.dataspaceconnector.service.usagecontrol.ContractManager.validateTransferContract(ContractManager.java:114) ~[classes!/:6.1.1]
	at io.dataspaceconnector.service.message.handler.validator.PolicyValidator.processInternal(PolicyValidator.java:77) ~[classes!/:6.1.1]
	at io.dataspaceconnector.service.message.handler.validator.PolicyValidator.processInternal(PolicyValidator.java:44) ~[classes!/:6.1.1]
	at io.dataspaceconnector.service.message.handler.validator.base.IdsValidator.process(IdsValidator.java:39) ~[classes!/:6.1.1]
	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:66) ~[camel-support-3.11.1.jar!/:3.11.1]

...

2021-09-08 09:28:03,303 https-jsse-nio-8080-exec-5 WARN  org.apache.camel.spring.spi.TransactionErrorHandler - Transaction rollback (0x4598961d) redelivered(false) for (MessageId: 7E6860D94210750-0000000000000F9A on ExchangeId: 7E6860D94210750-0000000000000F9A) caught: io.dataspaceconnector.common.exception.ContractException: The issuer connector does not correspond to the signed consumer.
```

**Comment by sebplorenz** [comment]
Hi, I'm still getting this error with DSC 6.1.1 between DB and IVI connector in DRM. I'm trying to guess the reason for the error and to find a workaround. But what does it mean "The issuer connector does not correspond to the signed consumer"?

**Comment by sebplorenz** [comment]
And still getting this error with 6.2.0
